name: MLDokio
version: ${project.version}
main: ru.armagidon.mldokio.MLDokio
api-version: 1.16
depend: [ProtocolLib]
authors: [Armagidon_MC]
description: Gives you opportunity to create a music in minecraft
